version: '3.8'

services:
  simplefileconverter:
    build:
      context: ..                         # repository root containing src/ folder
      dockerfile: src/SimpleFileConverter.API/Dockerfile
    ports:
      - '5000:5000'  # HTTP endpoint (mapped to container's 5000)
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped